import { type ReactElement } from "react";
// import localFont from "next/font/local";
import Head from "next/head";

/* const karla = Karla({
  subsets: ["latin"],
  variable: "--font-karla",
});

const myFont = localFont({
  src: "../../assets/fonts/fengardoneue_regular-webfont.woff",
  variable: "--font-display",
});
const myFont2 = localFont({
  src: "./VG5000-Regular_web.woff2",
  variable: "--font-display-2",
}); */

const SiteLayout = ({
  children,
  pageTitle,
}: {
  children: ReactElement;
  pageTitle?: string;
}) => {
  return (
    <>
      <Head>
        <title>Piros Photography{pageTitle ? ` - ${pageTitle}` : null}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
      // className={`font-sans`}
      /*         style={{
          ...myFont2.style,
        }} */
      >
        {/* <main className={`${myFont.variable} ${myFont2.variable} font-sans`}> */}
        {children}
      </main>
      {/* <main className={`${karla.variable} font-sans`}>{children}</main> */}
    </>
  );
};

export default SiteLayout;
