import Head from "next/head";
import { type ReactElement } from "react";

const SiteLayout = ({
  children,
  pageTitle,
}: {
  children: ReactElement;
  pageTitle?: string;
}) => {
  return (
    <>
      <Head>
        <title>Piros Photography{pageTitle ? ` - ${pageTitle}` : null}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>{children}</main>
    </>
  );
};

export default SiteLayout;
