import {
  ChatText,
  Check,
  DotsThreeVertical,
  Gear,
  Info,
  PencilSimple,
  SignOut,
  Spinner,
  Trash,
  UserCircle,
  UserCircleGear,
  Warning,
  WarningCircle,
} from "@phosphor-icons/react";

export {
  Spinner as SpinnerIcon,
  UserCircle as UserIcon,
  ChatText as UserCommentIcon,
  Gear as UserManageAccountIcon,
  SignOut as SignOutIcon,
  Warning as AlertIcon,
  WarningCircle as ErrorIcon,
  Check as SuccessIcon,
  Info as InfoIcon,
  DotsThreeVertical as UserMenuIcon,
  PencilSimple as EditIcon,
  Trash as DeleteIcon,
  UserCircleGear as AdminIcon,
};
